// <auto-generated />
using System;
using FacturacionVERIFACTU.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FacturacionVERIFACTU.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260407200055_ChangeSuperAdminPlan")]
    partial class ChangeSuperAdminPlan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<string>("DireccionEntrega")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion_entrega");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<bool>("Facturado")
                        .HasColumnType("boolean")
                        .HasColumnName("facturado");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_entrega");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<int?>("PresupuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("presupuesto_id");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.Property<decimal>("TotalRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_recargo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FacturaId");

                    b.HasIndex("PresupuestoId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("albaranes");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueada");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<decimal>("CuotaRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cuota_recargo");

                    b.Property<decimal?>("CuotaRetencion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cuota_retencion");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<bool>("EnviadaVERIFACTU")
                        .HasColumnType("boolean")
                        .HasColumnName("enviada_verifactu");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<DateTime?>("FechaEnvioVERIFACTU")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio_verifactu");

                    b.Property<string>("Huella")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella");

                    b.Property<string>("HuellaAnterior")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("huella_anterior");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("NumeroFacturaRectificada")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero_factura_rectificada");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PorcentajeRetencion")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<byte[]>("QRVerifactu")
                        .HasColumnType("bytea")
                        .HasColumnName("qr_verifactu");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoFacturaVERIFACTU")
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)")
                        .HasColumnName("tipo_factura_verifactu");

                    b.Property<string>("TipoRectificacion")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_rectificacion");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.Property<decimal?>("TotalRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_recargo");

                    b.Property<string>("UrlVERIFACTU")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("url_verifactu");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("API.Data.Entities.LineaAlbaran", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbaranId")
                        .HasColumnType("integer")
                        .HasColumnName("albaran_id");

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<decimal>("ImporteDescuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_descuento");

                    b.Property<decimal>("ImporteIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_iva");

                    b.Property<decimal>("ImporteRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_recargo");

                    b.Property<decimal>("IvaPercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva_percent_snapshot");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("RePercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("re_percent_snapshot");

                    b.Property<int?>("TipoImpuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_impuesto_id");

                    b.HasKey("Id");

                    b.HasIndex("AlbaranId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoImpuestoId");

                    b.ToTable("lineas_albaran");
                });

            modelBuilder.Entity("API.Data.Entities.LineaFactura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<int>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<decimal>("ImporteIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_iva");

                    b.Property<decimal>("ImporteRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_recargo");

                    b.Property<decimal>("IvaPercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva_percent_snapshot");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("RePercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("re_percent_snapshot");

                    b.Property<int?>("TipoImpuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_impuesto_id");

                    b.HasKey("Id");

                    b.HasIndex("FacturaId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoImpuestoId");

                    b.ToTable("lineas_factura");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.CierreEjercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActualizadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actualizado_en");

                    b.Property<DateTime>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("creado_en");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<bool>("EnviadoVERIFACTU")
                        .HasColumnType("boolean")
                        .HasColumnName("enviado_verifactu");

                    b.Property<bool>("EstaAbierto")
                        .HasColumnType("boolean")
                        .HasColumnName("esta_abierto");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_envio");

                    b.Property<DateTime?>("FechaReapertura")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_reapertura");

                    b.Property<string>("HashFinal")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("hash_final");

                    b.Property<string>("MotivoReapertura")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_reapertura");

                    b.Property<string>("RutaLibroFacturas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_libro_facturas");

                    b.Property<string>("RutaResumenIVA")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ruta_resumen_iva");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalBaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_base_imponible");

                    b.Property<int>("TotalFacturas")
                        .HasColumnType("integer")
                        .HasColumnName("total_facturas");

                    b.Property<decimal>("TotalIVA")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.Property<decimal>("TotalImporte")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_importe");

                    b.Property<decimal>("TotalRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_recargo");

                    b.Property<decimal>("TotalRetencion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_retencion");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.Property<int?>("UsuarioReaperturaId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_reapertura_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioReaperturaId");

                    b.HasIndex("TenantId", "Ejercicio", "EstaAbierto")
                        .IsUnique()
                        .HasFilter("esta_abierto = false");

                    b.ToTable("cierres_ejercicios");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificaion");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NotasFiscales")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas_fiscales");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pais");

                    b.Property<decimal?>("PorcentajeRetencionDefecto")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_retencion_defecto");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<bool>("RegimenRecargoEquivalencia")
                        .HasColumnType("boolean")
                        .HasColumnName("regimen_recargo_equivalencia");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoCliente")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "NIF")
                        .IsUnique();

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.LineaPresupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cantidad");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe");

                    b.Property<decimal>("ImporteDescuento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_descuento");

                    b.Property<decimal>("ImporteIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_iva");

                    b.Property<decimal>("ImporteRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("importe_recargo");

                    b.Property<decimal>("IvaPercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("iva_percent_snapshot");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PorcentajeDescuento")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_descuento");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio_unitario");

                    b.Property<int>("PresupuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("presupuesto_id");

                    b.Property<int?>("ProductoId")
                        .HasColumnType("integer")
                        .HasColumnName("producto_id");

                    b.Property<decimal>("RePercentSnapshot")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("re_percent_snapshot");

                    b.Property<int?>("TipoImpuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_impuesto_id");

                    b.HasKey("Id");

                    b.HasIndex("PresupuestoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TipoImpuestoId");

                    b.ToTable("lineas_presupuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("token");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean")
                        .HasColumnName("used");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("password_reset_tokens");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseImponible")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_imponible");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer")
                        .HasColumnName("cliente_id");

                    b.Property<decimal?>("CuotaRetencion")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cuota_retencion");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado");

                    b.Property<int?>("FacturaId")
                        .HasColumnType("integer")
                        .HasColumnName("factura_id");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaValidez")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_validez");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("numero");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("observaciones");

                    b.Property<decimal?>("PorcentajeRetencion")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_retencion");

                    b.Property<int>("SerieId")
                        .HasColumnType("integer")
                        .HasColumnName("serie_id");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("TotalIva")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_iva");

                    b.Property<decimal?>("TotalRecargo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_recargo");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("SerieId");

                    b.HasIndex("TenantId", "Numero")
                        .IsUnique();

                    b.ToTable("presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TipoImpuestoId")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_impuesto_id");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unidad");

                    b.HasKey("Id");

                    b.HasIndex("TipoImpuestoId");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique();

                    b.ToTable("productos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.ReciboServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("integer")
                        .HasColumnName("creado_por_id");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<decimal>("ImporteBase")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("importe_base");

                    b.Property<decimal>("ImporteIva")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("importe_iva");

                    b.Property<decimal>("ImporteTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("importe_total");

                    b.Property<int>("NumeroRecibo")
                        .HasColumnType("integer")
                        .HasColumnName("numero_recibo");

                    b.Property<DateTime>("PeriodoDesde")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_dsde");

                    b.Property<DateTime>("PeriodoHasta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("periodo_hasta");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_iva");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("NumeroRecibo")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("recibos_servicio");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<bool>("Bloqueada")
                        .HasColumnType("boolean")
                        .HasColumnName("bloqueada");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("descripcion");

                    b.Property<int>("Ejercicio")
                        .HasColumnType("integer")
                        .HasColumnName("ejercicio");

                    b.Property<string>("Formato")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("formato");

                    b.Property<int>("ProximoNumero")
                        .HasColumnType("integer")
                        .HasColumnName("proximo_numero");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo_documento");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Codigo", "Ejercicio", "TipoDocumento")
                        .IsUnique();

                    b.ToTable("series_facturacion");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Ciudad")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ciudad");

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaFinPlan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin_plan");

                    b.Property<DateTime>("FechaInicioPlan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_incicio_plan");

                    b.Property<string>("Folio")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("folio");

                    b.Property<string>("Hoja")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("hoja");

                    b.Property<string>("Inscripcion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("inscripcion");

                    b.Property<string>("Libro")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("libro");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("bytea")
                        .HasColumnName("logo");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("nif");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("NotasAdmin")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notas_admin");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("plan");

                    b.Property<decimal>("PrecioMensual")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio_mensual");

                    b.Property<string>("Provincia")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provincia");

                    b.Property<string>("RegistroMercantil")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("registro_mercantil");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schema");

                    b.Property<string>("Seccion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seccion");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("telefono");

                    b.Property<string>("Tomo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tomo");

                    b.HasKey("Id");

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.HasIndex("Schema")
                        .IsUnique()
                        .HasDatabaseName("IX_tenants_schema");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<int?>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<decimal>("PorcentajeIva")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_iva");

                    b.Property<decimal>("PorcentajeRecargo")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("porcentaje_recargo");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nombre")
                        .IsUnique();

                    b.ToTable("tipos_impuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaCreaccion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creaccion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("rol");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_acceso");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Albaranes")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API.Data.Entities.Factura", "Factura")
                        .WithMany("Albaranes")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Albaranes")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", "Serie")
                        .WithMany("Albaranes")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Factura");

                    b.Navigation("Presupuesto");

                    b.Navigation("Serie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Facturas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", "Serie")
                        .WithMany("Facturas")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Serie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.LineaAlbaran", b =>
                {
                    b.HasOne("API.Data.Entities.Albaran", "Albaran")
                        .WithMany("Lineas")
                        .HasForeignKey("AlbaranId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasAlbaran")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", "TipoImpuesto")
                        .WithMany("LineasAlbaran")
                        .HasForeignKey("TipoImpuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Albaran");

                    b.Navigation("Producto");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("API.Data.Entities.LineaFactura", b =>
                {
                    b.HasOne("API.Data.Entities.Factura", "Factura")
                        .WithMany("Lineas")
                        .HasForeignKey("FacturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasFactura")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", "TipoImpuesto")
                        .WithMany("LineasFactura")
                        .HasForeignKey("TipoImpuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Factura");

                    b.Navigation("Producto");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.CierreEjercicio", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Usuario", "UsuarioReapertura")
                        .WithMany()
                        .HasForeignKey("UsuarioReaperturaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");

                    b.Navigation("Usuario");

                    b.Navigation("UsuarioReapertura");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Clientes")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.LineaPresupuesto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", "Presupuesto")
                        .WithMany("Lineas")
                        .HasForeignKey("PresupuestoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Producto", "Producto")
                        .WithMany("LineasPresupuesto")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", "TipoImpuesto")
                        .WithMany("LineasPresupuesto")
                        .HasForeignKey("TipoImpuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Presupuesto");

                    b.Navigation("Producto");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Cliente", "Cliente")
                        .WithMany("Presupuestos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", "Serie")
                        .WithMany("Presupuestos")
                        .HasForeignKey("SerieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Serie");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Productos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", "TipoImpuesto")
                        .WithMany("Productos")
                        .HasForeignKey("TipoImpuestoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tenant");

                    b.Navigation("TipoImpuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.ReciboServicio", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.RefreshToken", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Series")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("TipoImpuestos")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Usuario", b =>
                {
                    b.HasOne("FacturacionVERIFACTU.API.Data.Entities.Tenant", "Tenant")
                        .WithMany("Usuarios")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("API.Data.Entities.Albaran", b =>
                {
                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("API.Data.Entities.Factura", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Cliente", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Facturas");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Presupuesto", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Lineas");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Producto", b =>
                {
                    b.Navigation("LineasAlbaran");

                    b.Navigation("LineasFactura");

                    b.Navigation("LineasPresupuesto");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.SerieNumeracion", b =>
                {
                    b.Navigation("Albaranes");

                    b.Navigation("Facturas");

                    b.Navigation("Presupuestos");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.Tenant", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Productos");

                    b.Navigation("Series");

                    b.Navigation("TipoImpuestos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("FacturacionVERIFACTU.API.Data.Entities.TipoImpuesto", b =>
                {
                    b.Navigation("LineasAlbaran");

                    b.Navigation("LineasFactura");

                    b.Navigation("LineasPresupuesto");

                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
